# Generated by Django 5.1.1 on 2024-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=50, verbose_name='Nome do filme')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo do filme')),
            ],
        ),
    ]
