# Generated by Django 5.1.3 on 2024-11-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
